GET http://localhost:3001/conversations/45

###

GET http://localhost:3001/users?searchInput=Mauricio

###

PUT http://localhost:3001/conversations/2/updatetitle
Content-Type: application/json

{
    "title": "hola"
}

###
POST http://localhost:3001/users/register
Content-Type: application/json

{
    "firstName": "Juan",
    "lastName": "Ramos",
    "email": "JuanRamos@gmail.com",
    "username":"JuanR",
    "password": "JPRR44"
}

