GET http://localhost:3001/conversations/45

###

GET http://localhost:3001/users?searchInput=Mauricio

###

PUT http://localhost:3001/conversations/2/updatetitle
Content-Type: application/json

{
    "title": "hola"
}

###
POST http://localhost:3001/users/register
Content-Type: application/json

{
    "firstName": "Mauricio",
    "lastName": "Duran",
    "email": "mauduran4@gmail.com",
    "username":"mau4duran",
    "password": "is716122"
}

###
GET http://localhost:3001/users/register

###
POST http://localhost:3001/users/login
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdWR1cmFuNEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6Im1hdTRkdXJhbiIsImlhdCI6MTU5NzI4OTIwNywiZXhwIjoxNTk3Mzc1NjA3fQ.4yWY9LhmaP0ZnSrABieNrrnjdw0TR_w-fZWMm84pMOY

{
    "username":"mau4duran",
    "password": "is716122"
}