GET http://localhost:3001/conversations/45

###

GET http://localhost:3001/users?searchInput=mau4duran

###

PUT http://localhost:3001/conversations/2/updatetitle
Content-Type: application/json

{
    "title": "hola"
}

###
POST http://localhost:3001/users/register
Content-Type: application/json

{
    "firstName": "Mauricio",
    "lastName": "Duaran",
    "email": "mau4duran@gmail.com",
    "username":"mau4duran",
    "password": "123456"
}

###
GET http://localhost:3001/users/login

###
POST http://localhost:3001/users/login
Content-Type: application/json

{
    "username": "mau4duran",
    "password": "123456"
}